version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/crown-court-contribution"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Gradle"
      include: "scope"

