version: 2.1

# ------------------
# EXECUTORS
# ------------------
executors:
  cloud-platform-executor:
    resource_class: small
    docker:
      - image: ministryofjustice/cloud-platform-tools
    working_directory: ~/laa-crown-court-contribution/crown-court-contribution
  build-executor:
    docker:
      - image: cimg/openjdk:17.0.4
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.workers.max=2"
    working_directory: ~/laa-crown-court-contribution/crown-court-contribution

# ------------------
# COMMANDS
# ------------------
commands:
  checkout_and_decrypt:
    steps:
      - checkout
      - run:
          name: Decrypt secrets
          command: |
            echo "${GIT_CRYPT_KEY}" | base64 -d > git-crypt.key
            git-crypt unlock git-crypt.key

  checkout_and_attach:
    steps:
      - checkout:
          path: ~/laa-crown-court-contribution
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true

  deploy-to:
    description: >
      Deploy image to the specified environment
    parameters:
      environment:
        description: Destination environment
        type: string
      token:
        description: CircleCI Service account token
        type: string
    steps:
      - checkout_and_decrypt
      - run:
          name: Authenticate with cluster
          command: |
            echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./ca.crt
            kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./ca.crt --server=https://${K8S_CLUSTER_NAME}
            kubectl config set-credentials circleci --token=<< parameters.token >>
            kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci --namespace=laa-crown-court-contribution-<< parameters.environment >>
            kubectl config use-context ${K8S_CLUSTER_NAME}
            kubectl --namespace=laa-crown-court-contribution-<< parameters.environment >> get pods
      - run:
          name: Upgrade helm chart
          command: |
            helm upgrade laa-crown-court-contribution ./helm_deploy/laa-crown-court-contribution/. \
                          --install --wait \
                          --namespace=laa-crown-court-contribution-<< parameters.environment >> \
                          --values ./helm_deploy/laa-crown-court-contribution/values-<< parameters.environment >>.yaml \
                          --set image.tag="${CIRCLE_SHA1}"

# ------------------
# JOBS
# ------------------
jobs:
  build:
    executor: build-executor
    steps:
      - checkout:
          path: ~/laa-crown-court-contribution
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Install Dependencies
          command: ./gradlew build -x test
      - run:
          name: Run SonarQube
          command: ./gradlew sonarqube -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.organization=${SONAR_ORG}
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - build

  test_and_assemble:
    executor: build-executor
    steps:
      - checkout_and_attach
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Run tests
          command: ./gradlew test
      #      - run:
      #          name: Generate code coverage report
      #          command: ./gradlew jacocoTestReport
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
      #     - store_artifacts:
      #         path: build/reports/jacoco/test/html
      - run:
          name: Assemble JAR
          command: ./gradlew assemble
      - store_artifacts:
          path: build/libs

  build_and_push_image:
    executor: cloud-platform-executor
    steps:
      - checkout_and_attach
      - run:
          name: Build docker image
          command: |
            docker build \
            --build-arg COMMIT_ID=${CIRCLE_SHA1} \
            --build-arg BUILD_TAG=${CIRCLE_SHA1} \
            --build-arg APP_BRANCH=${CIRCLE_BRANCH} \
            --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) \
            -t app .
      - run:
          name: Push to ecr
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
            docker tag app "$AWS_ECR_ACCOUNT_URL/laa-crime-apps-team/laa-crown-court-contribution-dev-ecr:${CIRCLE_SHA1}"
            docker push "$AWS_ECR_ACCOUNT_URL/laa-crime-apps-team/laa-crown-court-contribution-dev-ecr:${CIRCLE_SHA1}"

  deploy-dev:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: dev
          token: ${CIRCLE_CI_TOKEN_DEV}

  deploy-test:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: test
          token: ${CIRCLE_CI_TOKEN_TEST}

  deploy-uat:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: uat
          token: ${CIRCLE_CI_TOKEN_UAT}

  deploy-staging:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: staging
          token: ${CIRCLE_CI_TOKEN_STAGING}

  deploy-prod:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: prod
          token: ${CIRCLE_CI_TOKEN_PROD}

# ------------------
# WORKFLOWS
# ------------------
workflows:
  version: 2

  build-deploy-master:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

      - test_and_assemble:
          requires:
            - build

      - build_and_push_image:
          requires:
            - test_and_assemble

      - deploy-dev:
          requires:
            - build_and_push_image

      - hold_install_on_test:
          type: approval
          requires:
            - build_and_push_image

      - deploy-test:
          requires:
            - hold_install_on_test

      - hold_install_on_uat:
          type: approval
          requires:
            - build_and_push_image

      - deploy-uat:
          requires:
            - hold_install_on_uat

      - hold_install_on_staging:
          type: approval
          requires:
            - build_and_push_image

      - deploy-staging:
          requires:
            - hold_install_on_staging

      - hold_install_on_prod:
          type: approval
          requires:
            - build_and_push_image

      - deploy-prod:
          requires:
            - hold_install_on_prod

  build-deploy-branch:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main

      - test_and_assemble:
          requires:
            - build

      - build_and_push_image:
          requires:
            - test_and_assemble

      - hold_install_on_dev:
          type: approval
          requires:
            - build_and_push_image

      - deploy-dev:
          requires:
            - hold_install_on_dev

      - hold_install_on_test:
          type: approval
          requires:
            - build_and_push_image

      - deploy-test:
          requires:
            - hold_install_on_test

      - hold_install_on_uat:
          type: approval
          requires:
            - build_and_push_image

      - deploy-uat:
          requires:
            - hold_install_on_uat

      - hold_install_on_staging:
          type: approval
          requires:
            - build_and_push_image

      - deploy-staging:
          requires:
            - hold_install_on_staging
