{{- if .Values.scheduledDowntime.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "laa-crown-court-contribution.fullname" . }}-shutdown
  labels:
    {{- include "laa-crown-court-contribution.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.scheduledDowntime.shutdown }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      template:
        spec:
          containers:
            - name: cloud-platform-tools
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
              image: ministryofjustice/cloud-platform-tools
              args:
                - kubectl
                - scale
                - deploy
                - {{ include "laa-crown-court-contribution.fullname" . }}
                - --replicas=0
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.scheduledDowntime.serviceAccountName }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "laa-crown-court-contribution.fullname" . | trunc 43 }}-startup
  labels:
    {{- include "laa-crown-court-contribution.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.scheduledDowntime.startup }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      template:
        spec:
          containers:
            - name: cloud-platform-tools
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
              image: ministryofjustice/cloud-platform-tools
              args:
                - kubectl
                - scale
                - deploy
                - {{ include "laa-crown-court-contribution.fullname" . }}
                - --current-replicas=0
                - --replicas={{ .Values.replicaCount }}
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.scheduledDowntime.serviceAccountName }}
{{- end }}