{{- if .Values.actuator.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "laa-crown-court-contribution.fullname" .  }}-monitoring
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "laa-crown-court-contribution.selectorLabels" . | nindent 6 }}
  endpoints:
    {{- if not (eq (toString .Values.actuator.port) "http") }}
    - port: actuator
    {{- else }}
    - port: http
    {{- end }}
      interval: {{ .Values.actuator.metrics.scrapeInterval }}
      path: {{ .Values.actuator.metrics.path }}
{{- end }}