server:
  port: 8088

management:
  server:
    port: 8098
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus


spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
