server:
  port: 8089

management:
  server:
    port: 8098
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    propagation:
      type: w3c,b3

spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

  security:
    oauth2:
      client:
        provider:
          maat-api:
            token-uri: ${MAAT_API_OAUTH_URL}
          hardship:
            token-uri: ${HARDSHIP_API_OAUTH_URL}
        registration:
          maat-api:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          hardship:
            client-id: ${HARDSHIP_API_OAUTH_CLIENT_ID}
            client-secret: ${HARDSHIP_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
      resource-server:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

services:
  maat-api:
    base-url: ${MAAT_API_BASE_URL}
    assessments-domain: ${services.maat-api.base-url}/api/internal/v1/assessment
    contribution-endpoints:
      base-url: ${services.maat-api.assessments-domain}/contributions
      find-url: ${services.maat-api.contribution-endpoints.base-url}/{repId}
      summary-url: ${services.maat-api.assessments-domain}/contributions/{repId}/summary
      get-appeal-amount-url: ${services.maat-api.assessments-domain}/contribution-appeal/caty-case-type/{caseType}/apty-code/{appealType}/cc-outcome/{outcome}/assessmentResult/{assessmentResult}
      get-rep-order-url: ${services.maat-api.assessments-domain}/rep-orders/{repId}
      contribs-parameters-url: ${services.maat-api.assessments-domain}/contribution-calc-params/{effectiveDate}
    correspondence-state-endpoints:
      base-url: ${services.maat-api.assessments-domain}/rep-orders/{repId}/correspondence-state
    rep-order-endpoints:
      find-outcome-url: ${services.maat-api.assessments-domain}/rep-orders/cc-outcome/reporder/{repId}
  hardship-api:
    base-url: ${HARDSHIP_API_BASE_URL}
    hardship-endpoints:
      calculate-hardship-for-detail-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/calculate-hardship-for-detail

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.contribution
  api-docs:
    path: /open-api/api-docs

  swagger-ui:
    path: /open-api/swagger-ui.html
    operationsSorter: method

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: ${SENTRY_SAMPLE_RATE}

retry-config:
  max-retries: 3
  min-back-off-period: 5
  jitter-value: 0.75
