server:
  port: 8087

management:
  server:
    port: 8098
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

  security:
    oauth2:
      client:
        provider:
          maat-api:
            token-uri: ${MAAT_API_OAUTH_URL}
        registration:
          maat-api:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials

services:
  maat-api:
    base-url: ${MAAT_API_BASE_URL}
    assessments-domain: /api/internal/v1/assessment
    contribution-endpoints:
      base-url: ${services.maat-api.assessments-domain}/contributions
      find-url: ${services.maat-api.assessments-domain.contribution-endpoints.base-url}/{repId}
      get-appeal-amount-url: ${services.maat-api.assessments-domain}/contribution-appeal
    correspondence-state-endpoints:
      base-url: ${services.maat-api.assessments-domain}/correspondence-state
      find-url: ${services.maat-api.assessments-domain.contribution-endpoints.base-url}/{repId}

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: 0.05
