--liquibase formatted sql
--changeset muthus:02-correspondence-templates-table-create
CREATE TABLE IF NOT EXISTS crown_court_contribution.CORRESPONDENCE_TEMPLATES
(
    ID INTEGER,
    COTY_CORRESPONDENCE_TYPE VARCHAR(20),
    TEMPLATE VARCHAR(20),
    DESCRIPTION VARCHAR(250),
    EFFECTIVE_DATE DATE,
    CONSTRAINT COTE_PK       PRIMARY KEY (ID),
    CONSTRAINT COTE_UK UNIQUE (ID, EFFECTIVE_DATE, TEMPLATE, COTY_CORRESPONDENCE_TYPE)
    );