--liquibase formatted sql
--changeset venkatv:04-correspondence-rules-table-create
CREATE TABLE IF NOT EXISTS crown_court_contribution.correspondence_rules
(
    ID INTEGER,
    MEANS_RESULT VARCHAR(10),
    MCOO_OUTCOME VARCHAR(50),
    DATE_FROM TIMESTAMP NOT NULL,
    DATE_TO	TIMESTAMP,
    COTE_ID	INTEGER,
    CALC_CONTRIBS VARCHAR(1) NOT NULL,
    IOJ_RESULT VARCHAR(4),
    CCOO_OUTCOME VARCHAR(50),
    UPLIFT_COTE_ID INTEGER,
    INIT_RESULT VARCHAR(10),
    REASSESSMENT_COTE_ID INTEGER
    CONSTRAINT unique_corr_rule UNIQUE (MEANS_RESULT, MCOO_OUTCOME, CCOO_OUTCOME, IOJ_RESULT),
    CONSTRAINT CORU_COTE_UPLIFT_FK FOREIGN KEY (UPLIFT_COTE_ID)
        REFERENCES crown_court_contribution.CORRESPONDENCE_TEMPLATES (ID),
    CONSTRAINT CORU_COTE_FK FOREIGN KEY (COTE_ID)
        REFERENCES crown_court_contribution.CORRESPONDENCE_TEMPLATES (ID),
    CONSTRAINT CORU_COTE_REASS_FK FOREIGN KEY (REASSESSMENT_COTE_ID)
        REFERENCES crown_court_contribution.CORRESPONDENCE_TEMPLATES (ID)
    );