# Default values for laa-crown-court-contribution.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-crime-apps-team/laa-crown-court-contribution-dev-ecr
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: latest

sentry:
  sampleRate: 0.05

aws_region: eu-west-2

java:
  host_env: uat

jwt:
  issuerUri: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_TXQgAwM8B

maatApi:
  baseUrl: https://maat-cd-api.uat.legalservices.gov.uk/api/internal/v1/assessment
  oauthUrl: https://maat-cd-api-uat.auth.eu-west-2.amazoncognito.com/oauth2/token

hardshipApi:
  baseUrl: http://laa-crime-hardship.laa-crime-hardship-uat.svc.cluster.local/api/internal/v1/hardship
  oauthUrl: https://laa-crime-auth-hardship.auth.eu-west-2.amazoncognito.com/oauth2/token

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "laa-crown-court-contribution"

service:
  type: ClusterIP
  port: 80
  targetPort: 8089

ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: "laa-crown-court-contribution-laa-crown-court-contribution-uat-green"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "300"
  externalAnnotations: {}
  hosts:
    - host: laa-crown-court-contribution-uat.apps.live.cloud-platform.service.justice.gov.uk
      paths: [ "/" ]
  tls: []
  className: default

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

actuator:
  metrics:
    enabled: true
    scrapeInterval: 15s
    path: /actuator/prometheus
  health:
    path: /actuator/health
  port: 8098
  liveness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5

scheduledDowntime:
  enabled: true
  # Start at 6am UTC Monday-Friday
  startup: '0 6 * * 1-5'
  # Stop at 10pm UTC Monday-Friday
  shutdown: '0 22 * * 1-5'
  serviceAccountName: scheduled-downtime-serviceaccount

logging:
  level: INFO